enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
compression-level = 9

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
build-mode = "both"

[X]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "both"
version = "10.48.0"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
